backend/.gitignore, backend/air.toml, backend/go.mod, backend/server.go
PR adds Air for live reloading during development and implements graceful shutdown to properly handle ongoing requests and clean up resources (e.g., database connections) when the server is terminated. The server now uses the http.Server's Shutdown method to wait for ongoing requests to finish before stopping, ensuring active database transactions are completed. A new .air.toml configuration file has also been added.
=> Dsd-26: Add Air for Live Reloading and Implement Graceful Shutdown

.gitignore
Set up `.gitignore` for future use and to include `package-lock.json` for the react app
=> DSD-33: Set up .gitignore

frontend/app/package.json, frontend/app/src/main.tsx
Init Router so others can start working on their pages
=> init react router with basic routes / route groups

frontend/app/src/pages/Error404.tsx
Fixed a broken link to the image
=> DSD-64 / DSD-71 fix: Rename sad_logo2.png to sad_logo.png in Error404.tsx

frontend/app/src/App.tsx, frontend/app/src/components/HeroBanner.tsx
=> DSD-66 feat: Create hero banner

frontend/app/src/components/FormExample.tsx, frontend/app/src/components/ReusableComponents.tsx, frontend/app/src/components/TimeRelatedFormExamples.tsx
I added some Form examples, we can pick them apart to build our own.
=> DSD-45: Create Reusable Components - add form examples

frontend/app/src/components/ModalComponent.tsx, frontend/app/src/components/reusableComponents/ButtonComponent.tsx, frontend/app/src/components/reusableComponents/CardComponent.tsx, frontend/app/src/components/reusableComponents/TableComponent.tsx, frontend/app/src/main.tsx, frontend/app/src/pages/AdminDashboard.tsx
=> Dsd 82 admin page

.env.example, backend/internal/smtp/smtp.go, backend/internal/smtp/smtp_test.go
**Description:**  
- Added `smtp.go` for loading SMTP configuration from environment variables.  
- Added `smtp_test.go` to test SMTP connectivity and authentication.  
- Implemented support for `SMTP_TLS_MODE` to allow both STARTTLS and direct TLS connections.  
- Updated `.env.example` to include SMTP-related environment variables.
=> Dsd 92 Add SMTP Configuration and Testing Files  

.github/workflows/backend.yml
=> DSD-120 chore: Update tests to fail if tests fail or coverage is too low

README.md
please pull and test these instructions on a fresh copy of the repository
=> DSD-117 Update README.md to include missing setup instructions

.env.example
PR updates .env.example file with instructions to obtain the secret from a team member with access to the Clerk account. This secret is required for webhook validation.
=> Dsd:121- Update ENV Example

.env.example, backend/internal/smtp/smtp.go, backend/internal/smtp/smtp_test.go
=> DSD-93 feat: Add send email functionality

backend/internal/smtp/smtp.go, backend/internal/smtp/smtp_test.go
Now it waits, trys again 3 times, and then logs and returns the error
=> DSD-94 Add better error handling for transient errors

backend/internal/smtp/smtp.go
=> DSD-95 Add logging upon successful send

.dockerignore, backend/Dockerfile, backend/Taskfile.yaml, backend/entrypoint.sh, backend/internal/db/queries/leases.sql, docker-compose.yml, setup.sh
This PR sets up live reload for the backend container using Air.
=> DSD-146: Enable live reload in backend container using Air

backend/Taskfile.yaml
Due to error during migration process.
=> Removed redirection to /dev/null of std/sterr

frontend/app/src/components/ModalComponent.tsx
I didn't upload this one when I was reuploading the missing files from a few days ago
=> Change the model componenet.tsx file to the most recent version

backend/internal/db/queries/complaints.sql
hopefully I did this right hahah lmk if I need to change anything smile
=> DSD 114 - Complaints SQLC Queries

backend/.air.toml, backend/Dockerfile, backend/entrypoint.sh, docker-compose.yml, frontend/app/Dockerfile
The frontend container build currently executes `npm i --no-audit --no-fund` without distinguishing between operating systems or the presence of a `package-lock.json` file. To ensure consistency and optimize package installation, update the Dockerfile to:
- Run `npm ci --no-audit --no-fund --unsafe-perm` on Windows when `package-lock.json` is present.
- Run `npm install --no-audit --no-fund --unsafe-perm` on Windows when `package-lock.json` is missing.
- Run `npm ci --no-audit --no-fund` on non-Windows systems when `package-lock.json` is present.
- Run `npm i --no-audit --no-fund` on non-Windows systems when `package-lock.json` is missing.
Additionally, the following changes were made:
- **Updated `docker-compose.yml`**: Ensured proper volume mounting and environment variable handling for …
=> DSD-153: Implement OS and Lockfile Check for NPM Install Command in Frontend Dockerfile

frontend/app/src/components/SidebarLinks.tsx, frontend/app/src/components/UniversalSidebar.tsx
As a developer, I need to make sure that the links on the sidebar are highlighted when the user is visiting said page.
Criteria for acceptance:
If the user is on the page, highlight the sidebar link that represents that page.
If the user is not on the page, make sure that the link is NOT highlighted.
=> DSD-105: init show active links in sidebar

.github/workflows/backend.yml
=> fix-workflow-2-electric-boogaloo

frontend/app/src/main.tsx, frontend/app/src/providers/layout/PreAuthedLayout.tsx
=> Fix Navbar Button Colors for right side navbar, and logo background contrast

frontend/app/src/main.tsx
=> Fix styling for login page

frontend/app/src/components/SidebarLinks.tsx, frontend/app/src/providers/layout/AuthenticatedLayout.tsx, frontend/app/src/styles/styles.scss
https://github.com/user-attachments/assets/c19dc3c4-eee8-4a0a-ad57-0158bcf43358
=> DSD-191: Fix Sidebar Responsiveness

backend/internal/db/generated/apartments.sql.go, backend/internal/db/queries/apartments.sql, backend/pkg/handlers/apartments.go, backend/server.go
implements apartment routes/handlers
=> Dsd 137 apartment handler

frontend/app/src/components/HomePageFeaturesComponent.tsx, frontend/app/src/components/reusableComponents/CardComponent.tsx, frontend/app/src/components/reusableComponents/PageTitleComponent.tsx, frontend/app/src/pages/AddTenant.tsx, frontend/app/src/pages/AdminApartmentSetupAndDetailsManagement.tsx, frontend/app/src/pages/AdminDashboard.tsx, frontend/app/src/pages/AdminViewEditLeases.tsx, frontend/app/src/pages/AdminWorkOrder.tsx, frontend/app/src/pages/TenantComplaintsAndWorkOrders.tsx, frontend/app/src/pages/TenantDashBoard.tsx
Check this Jira Ticket for Before and Afters, check the timestamps if you're wondering which is which:
https://baeyoojindev.atlassian.net/jira/software/projects/DSD/boards/1?selectedIssue=DSD-190
=> Dsd 190: fix titles on home page and pages

backend/internal/db/generated/complaints.sql.go, backend/internal/db/generated/parking_permits.sql.go, backend/internal/db/generated/work_orders.sql.go, backend/internal/db/queries/complaints.sql, backend/internal/db/queries/work_orders.sql, backend/pkg/handlers/user.go, backend/pkg/handlers/work_orders.go, backend/server.go
PR implements
/admin/tenants/{clerk_id}/work_orders
/admin/tenants/{clerk_id}/complaints 
this satisfies: Admin-specific endpoints to view work orders and complaints for a given tenant
=> Dsd-205: Admin Endpoints for Tenant Work Orders and Complaints

frontend/app/src/pages/TenantComplaintsAndWorkOrders.tsx
Changes the custom component, that displays the work orders and complaints for the tenant, to the actual <TableComponent /> we made.
VS (Old Way):
=> DSD-169: Incorporate TableComponent.tsx in the TenantComplaintsAndWorkOrders.tsx page

frontend/app/src/components/ModalComponent.tsx, frontend/app/src/components/reusableComponents/AlertComponent.tsx, frontend/app/src/components/reusableComponents/TableComponent.tsx, frontend/app/src/pages/AdminWorkOrder.tsx, frontend/app/src/styles/styles.scss
I figured it out. This PR required a lot of changes to what I previously built, but I got it working. When merging backend and frontend logic, I will need to make some backend integrations for updating databases when state variables for workOrders and complaints are changed, but here's a demo of I got:
https://github.com/user-attachments/assets/5ec2cc8c-c7be-4f5e-b27a-3304887cda5b
=> DSD-194: Clickable Modal for Admin Work Order Viewing & Editing

frontend/app/src/components/ModalComponent.tsx, frontend/app/src/components/reusableComponents/AlertComponent.tsx, frontend/app/src/components/reusableComponents/TableComponent.tsx, frontend/app/src/pages/AdminWorkOrder.tsx, frontend/app/src/pages/TenantDashBoard.tsx, frontend/app/src/styles/styles.scss
I hardcoded an inescapable modal in the tenant dashboard that forces the tenant to click onto the button to route to Documenso to sign their lease. At the moment, the URL is purposely incorrect, since backend integration for this step has not been implemented yet, but it will be integrated in the DSD-171 ticket coming soon.
=> DSD-178: Lease Frontend (Tenant)

README.md, frontend/app/src/components/HeroBanner.tsx, frontend/app/src/components/HomePageFAQs.tsx, frontend/app/src/components/UniversalSidebar.tsx, frontend/app/src/providers/layout/AuthenticatedLayout.tsx, frontend/app/src/providers/layout/PreAuthedLayout.tsx
Just doing this to make sure it gets done before code freeze :) It only touches readme and frontend text, nothing on the backend should have been changed
=> DSD-210 Change Frontend to say EZRA and not Rentdaddy

frontend/app/src/providers/ProtectedRoutes.tsx
https://github.com/user-attachments/assets/ee7cfcf1-1a27-43aa-9dd7-684dc2318d31
=> DSD 211: Init Auth Provider Loader Styles

frontend/app/src/components/HomePageFAQs.tsx
No more FAQs were thought of and they can just be added to the ones we have
=> DSD-215 chore: remove more faq button

frontend/app/src/components/HeroBanner.tsx
It still needs a back end to store or use it somewhere, but for now you can see the object in the console, not sure how we should handle that yet... and its a little late in the cohort for that... this is better than a 404
=> DSD-213 Feat: Replace dead link with contact info collecting modal

frontend/app/src/components/ChatBot.tsx
=> DSD-212 Change a to an in chatbot popup text 

frontend/app/src/components/SidebarLinks.tsx, frontend/app/src/providers/layout/AuthenticatedLayout.tsx
=> DSD 208: init fix sidebar scroll

frontend/app/src/components/SidebarLinks.tsx, frontend/app/src/main.tsx, frontend/app/src/pages/AddTenant.tsx
Thanks for the good idea @Dissurender
=> DSD-216 Change add tenant to manage tennat

frontend/app/src/providers/layout/AuthenticatedLayout.tsx, frontend/app/src/providers/layout/PreAuthedLayout.tsx, frontend/app/src/styles/styles.scss
No clicking these allowed :angry: 
Please :angel:
=> DSD-214 Disabled Footer Links

backend/internal/db/generated/apartments.sql.go, backend/internal/db/generated/complaints.sql.go, backend/internal/db/generated/leases.sql.go, backend/internal/db/generated/models.go, backend/internal/db/generated/users.sql.go, backend/internal/db/queries/users.sql, backend/internal/utils/dbSeeder.go, backend/pkg/handlers/apartments.go, frontend/app/src/components/SidebarLinks.tsx, frontend/app/src/components/reusableComponents/TableComponent.tsx, frontend/app/src/main.tsx, frontend/app/src/pages/AdminViewEditSmartLockers.tsx
=> Add Admin-View-Lockers-Page
